### ISSUE TITLE
XY-WFPOW question

### ISSUE THREAD

**Issue by tinkering4fun** [Phanty133/sinilink-wfpow-client#1]
Hi Phanty133,
I just came across this empty repository while looking for information about XY-WFPOW module ...
Do you you have any information about this module's serial protocol?

I have a problem getting my XY-6020L DC converter modules to work.
They are advertised as speaking Modbus, but they do not respond at all.

In the advertising pictures they are used with XY-WFPOW modules, thus I look for more information about (baudrate, protocol etc.)
Do this modules somehow advertise themselves on the serial port when powered up?

My goal is to bypass the Sinilink App and use bare TTL Serial interface of those DC converters to make a Solar Battery Charger.

Regards
Werner

**Comment by Phanty133** [comment]
Hey. Yeah I saw reference to Modbus too, but I haven't yet gotten around to figuring out the hardware comms. So far what I've done is reverse engineer their app and how to control the modules through the WiFi module. In short, the WiFi module connects to their own MQTT server at mq.sinilink.com. I've also identified most of the commands and arguments they use. Since I intended to use multiple of these modules on a local network, my intended (and successfully tested) solution is to spoof the sinilink domain to route to my own MQTT server to which I send commands from a webapp. In theory, Sinilink's MQTT server doesn't appear to be secured in any way, so I don't think there's anything preventing anyone from just using their server to communicate with your modules, indexed by their MAC address (a bit of a security risk, if you ask me). If this may be helpful, I'll spruce up my notes and make them less chaotic and publish them on the repo. I won't have access to my module until June, so I can't really be of much more help than this.

Good luck on the project and if you manage to figure out how to communicate it through hardware, let me know.

**Comment by tinkering4fun** [comment]
Wow ... this response was really fast :-)

Good news, I just got it to work!
While searching the Net, I recognized that there are also several other XY-something Modules which typically connect to the Sinilink App, but also support the Modbus protocol.  
Eventually I found the crucial hint at https://github.com/mathismoder/xy-wt04-mqtt where Mathis wrote  
 "_What took me a while was to find out the baudrate + address the module was talking at (115200)_."

In my case the correct baudrate setting is also 115200, where the seller's  documentation  says 9600 baud :-(
After additionally figuring out that on my XY-6020L device TX pin is input and need connected to RXD at the RS485 adapter *) I got a  response. 
_Unfortunately those pins are very seldom clearly labelled as  e.g. TXI / TXO  or  RXI / RXO to know about input/output_

As I use Modbus already for a while with different devices, things should now go easy ..., as long as the required register documentation is correct.
After some further tests, I will put my results for this XY-6020L DC Power Supply in a GitHub repository.

*) Of course, RS485 adapter is only required if you really want to have a Modbus with several devices connected. In case of 1:1 connection TTL is sufficient, and you simply need to adhere to the **Modbus RTU** protocol.  
As this protocol requires a CRC checksum, you may want to use some library, depending on your project.

Personally I do not like any dependencies from foreign services when controlling my local appliances.  
Thus I admire your domain spoofing approach :-)

Btw: 
In your project, it may also be an option to use e.g. ESP32 / ESP8266  and some Modbus RTU Master library to build a MQTT (or-something-else) / Serial gateway (as a replacement for the Sinilink WiFi module). Hardcore hackers would even flash new software to the WiFi module :-), which I do not recommend ...  
If cabling is not an issue, you could span a Modbus wire-pair, daisy chaining the devices.
In the Modbus paradigm, the devices are called Slaves (aka servers) and the controlling instance is known as master (aka client).  
Modbus over Serial line is called **Modbus RTU**, in contrast to Modbus TCP.

Regards

**Comment by Phanty133** [comment]
Thanks for the update! I wanted to interface with their module directly because it'd be less work for me since I have to deploy around a dozen of the converters for my particular use case, and in addition it'd save me the effort of figuring out how to interface the hardware directly + writing my own gateway. Took only around a day to reverse engineer their system thanks to Wireshark and APK decompilation tools :). Once I get my hands on the converter again, I'll figure out an approach to make the default firmware on the WiFi module more easily integrateable with projects (Which was the entire idea behind this repo :P). Though I still might have to look into directly interfacing with the converter with a micro for a different project, so your lead will definitely be helpful.
